# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoAccountKitNativeCode' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DemoAccountKitNativeCode
  pod 'RNAccountKit', :path => '../node_modules/react-native-facebook-account-kit/ios'

end
